# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

parameters:
  - name: target
    displayName: Build target
    type: string
    default: macos
    values:
    - macos
    - windows
    - linux
  
  - name: custom_choices
    type: object
    default:
    - Choice1
    - Choice2
    - Choice3

trigger:
- main

pool:
  name: sehal-local

steps:
  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | ./cli/pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm

  - script: |
      corepack enable
      corepack prepare pnpm@latest-9 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"
