# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: sehal-local

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      cd cli && npm install
    displayName: "Installing cli"
    
  - script: |
      cd cli && npm run unity:build -t macos -p ../../ -uv 2021.3.38f1 -n AzurePipelineTest -c -v
    displayName: "Building unity project"